export const STRINGS = {
  common: {
    app_name: "Cepat Belajar",
    loading: "Memuatkan...",
    error: "Ralat telah berlaku",
    save: "Simpan",
    cancel: "Batal",
    delete: "Padam",
    next: "Seterusnya",
    back: "Kembali",
    finish: "Tamat",
    retry: "Cuba Lagi",
  },
  auth: {
    title: "Cepat Belajar",
    subtitle: "Belajar Jadi Seronok!",
    login_btn: "Mula Belajar",
    student_btn: "Login Pelajar",
    admin_btn: "Login Admin",
    logout: "Log Keluar",
  },
  student: {
    greeting: "Hai,",
    daily_goal: "Aktiviti hari ini",
    learning_plan: "Pelan Pembelajaran Saya",
    subjects: "Subjek",
    topics: "Topik",
    streak_info: "Harian Streak",
    questions_done: "Soalan Tamat",
    progress: "Kemajuan",
    mastery: "Penguasaan",
    accuracy: "Akurasi",
    time_spent: "Masa Belajar",
    best_streak: "Streak Terbaik",
    sessions: "Sesi",
    summary_title: "Hebat!",
    summary_subtitle: "Anda telah menyelesaikan sesi ini.",
    redo_session: "Ulang Sesi",
    back_to_home: "Balik ke Utama",
    nav: {
      home: "Utama",
      learn: "Belajar",
      progress: "Kemajuan",
    }
  },
  admin: {
    dashboard: "Dashboard",
    subjects: "Subjek",
    students: "Pelajar",
    settings: "Tetapan",
    total_subjects: "Jumlah Subjek",
    total_questions: "Jumlah Soalan",
    total_students: "Jumlah Pelajar",
    weekly_attempts: "Percubaan Minggu Ini",
    recent_activity: "Aktiviti Terkini",
    student_summary: "Ringkasan Pelajar",
    add_subject: "Tambah Subjek",
    add_topic: "Tambah Topik",
    add_question: "Tambah Soalan",
    import_csv: "Import CSV",
    question_editor: "Editor Soalan",
  }
};
